# GitHub Sponsors and other funding links
# Add your sponsor or donation links below. Uncomment and fill as needed.

github: [ sillsdev ]
# patreon: your-patreon-username
# open_collective: your-collective
# ko_fi: your-kofi-username
# tidelift: npm/your-package-name
# community_bridge: your-project
# liberapay: your-liberapay
# issuehunt: your-issuehunt
# otechie: your-otechie
custom: ["https://give.sil.org/campaign/597654/donate"]
